# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_wHinuy0Se-Xh4sY_9vSm1A3x8kJdiOA
"""

import multiprocessing
import os
import time

def square(lock, x: int):
    with lock:
        print('square process id: {}'.format(os.getpid()))
        print('square: {}'.format(x * x))
        time.sleep(2)

def cube(lock, x: int):
    with lock:
        print('cube process id: {}'.format(os.getpid()))
        print('cube: {}'.format(x * x * x))
        time.sleep(2)



# t1 = time.time()

# square(10)
# cube(10)
# print('done')

# t_exec = time.time() - t1
# print('waktu eksekusi : ',t_exec)

if __name__ == "__main__":
    t1 = time.time()
    print('Main process id: {}'.format(os.getpid()))
    lock = multiprocessing.Lock()

    p1 = multiprocessing.Process(target=square, args=(lock, 10,))
    p2 = multiprocessing.Process(target=cube, args=(lock, 10,))


    p1.start()
    p2.start()

    p1.join()
    p2.join()


    print("done")
    t_exec = time.time() - t1
    print('waktu eksekusi : ',t_exec)